### ISSUE TITLE
performance of baselines in mimic-iii

### ISSUE THREAD

**Issue by Data-Designer** [pat-jj/GraphCare#2]
Hello, I appreciate the effort put into this work. However, upon executing the baseline code (for instance, gamenet), I've observed a significant deviation in performance compared to your reported figures. Notably, the PRAUC achieved is only 0.72, markedly lower than the expected 0.76 as per your report. This result is consistent with the PRAUC of approximately 0.72 also reported in Pyhealth. Despite thorough examination, I haven't identified any discernible differences between the two codebases.

**Comment by pat-jj** [comment]
@Data-Designer Hi, thanks for your interest in this work! The leaderboard of PyHealth was also reported and maintained by me.
The performance difference might be due to the different task definitions (e.g., `drug_recommendation_mimic3_fn` in `pyhealth.tasks`) we used. 
I will show the local modification on this later.

**Comment by pat-jj** [comment]
Hi, I found that I have already incorporate the task definition in the repo (in `graphcare_/task_fn.py`). Please also run `ehr_models.py` instead of `baselines.py` to reproduce the baseline results. Thank you!
We will sort the repo and release a more neat codebase in the future.
The following is a piece of running result I just obtained for GAMENet on MIMIC-III:
![image](https://github.com/pat-jj/GraphCare/assets/56672509/911aed7a-ddf7-42d0-b59f-a0f10d7499f2)
![image](https://github.com/pat-jj/GraphCare/assets/56672509/0160c93e-a94e-4048-aeb8-045972863ef8)

Please feel free to let me know if you have other questions.

**Comment by Data-Designer** [comment]
Many thanks!


| |
赵闯
|
|
***@***.***
|


---- Replied Message ----
| From | Patrick ***@***.***> |
| Date | 01/18/2024 15:23 |
| To | ***@***.***> |
| Cc | Zhao ***@***.***> ,
***@***.***> |
| Subject | Re: [pat-jj/GraphCare] performance of baselines in mimic-iii (Issue #2) |

Hi, I found that I have already incorporate the task definition in the repo (in graphcare_/task_fn.py). Please also run ehr_models.py instead of baselines.py to reproduce the baseline results. Thank you!
We will sort the repo and release a more neat codebase in the future.
The following is a piece of running result I just obtained for GAMENet on MIMIC-III:
image.png (view on web)
image.png (view on web)

Please feel free to let me know if you have other questions.
